---
title: 事务异常不回滚
date: 2021-06-14 21:02:50
tags:
---

# 日常Bug排查-抛异常不回滚

## Bug现场

最近有人反映java应用操作数据库的时候，抛异常不回滚

```
@Transacion(value="x") 
public void s1() throw MyException{ 
    update(1); 
    throwBusinessException();
    update(2); 
}
```

乍看上去没啥问题。

## 翻下Spring源码

Spring的源码，看下它在声明式事务中的处理逻辑到底是什么，于是翻到了这一段处理事务异常的代码:

```
TransactionAspectSupport.java
protected void completeTransactionAfterThrowing(TransactionInfo txInfo, Throwable ex) {
    if (txInfo.transactionAttribute.rollbackOn(ex)) {
    }else{
        // We don't roll back on this exception.
        // Will still roll back if TransactionStatus.isRollbackOnly() is true.
        // 在checkedException的时候,不会被rollBack,会commit!!!
    }
}
@Override
public boolean rollbackOn(Throwable ex) {
    return (ex instanceof RuntimeException || ex instanceof Error);
}
```

看代码逻辑就明白了，只有异常继承RuntimeException或者Error的时候才会回滚！





# 遇到异常，应用该如何回滚

## 应用Commit报错并不一定回滚

阐述一下当我们在事务Commit报错时候，数据库中的数据并不一定会是我们以为的回滚状态。
![图片](https://mmbiz.qpic.cn/mmbiz_png/yiaiaFLiaflYRTx1JrBPXUHGoBRoicHK5gNHiaLyDP0Z3m3atpmibPxNPZXt4jgSLF4jSDvictrMjyW5lxCIwQZVJyqlw/640)
在这种情况下，很明显的DB的数据肯定是处于已经提交的状态。而如果App认为是回滚状态，并基于这个信息去做操作的话，很明显会导致数据不一致。

## 非IO or 超时异常 也不一定回滚

可能有人会问了，是不是仅仅是IO异常或者超时异常才会出现这种不一定回滚的问题呢？这里还真不一定，笔者在一次Case中，就发现Oracle在commit的时候返回死锁异常时候，数据库内部的commit竟然也成功了!这就牵涉到数据库内部的处理了。

## 应用应该怎么做呢？

事实上，由于数据库保证了原子性。所以我们在遇到这种情况时候，需要从数据库中重建状态,而不是依赖现在应用里面的信息。所以遇到异常直接将流程结束，然后等定时任务等补单操作是个比较简单安全的做法。
当然，数据库中重建状态时候，也要考虑到上一个相应的commit还在commit的过程中,只不过这个commit非常慢而已。由于我们更新数据或者最终判断的时候往往会锁住数据,而数据库一般都是采用了二阶段锁(S2PL)。
![图片](https://mmbiz.qpic.cn/mmbiz_png/yiaiaFLiaflYRTx1JrBPXUHGoBRoicHK5gNHkR7NgO8BrRiaenicYHGmaENN70MHSpYRdOjLGm3MiayPCet0syU1eSXLA/640)
在上一个commit成功提交之后，我们对相应数据的操作才会执行下去。所以只要小心的控制好锁的范围，数据一致性还是能保证的。



